#include "docker/TemplateWriter.h"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QTextStream>

#include "config/ConfigSchema.h"
#include "core/AppPaths.h"
#include "core/Logger.h"
#include "core/StringUtil.h"
#include "server/ServerRecord.h"

namespace mcsm {
namespace {

/// Writes text with LF line endings (important: server.properties and shell
/// scripts must not contain CRLF, otherwise the shell reports "not found").
bool writeLf(const QString &path, const QString &content, QString *error)
{
    QDir().mkpath(QFileInfo(path).absolutePath());
    QFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Truncate)) {
        if (error)
            *error = QStringLiteral("cannot write %1").arg(path);
        return false;
    }
    QByteArray bytes = content.toUtf8();
    bytes.replace("\r\n", "\n");
    file.write(bytes);
    file.close();
    return true;
}

/// .cmd files are parsed more reliably with CRLF line endings.
bool writeCrlf(const QString &path, const QString &content, QString *error)
{
    QDir().mkpath(QFileInfo(path).absolutePath());
    QFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Truncate)) {
        if (error)
            *error = QStringLiteral("cannot write %1").arg(path);
        return false;
    }
    QString text = content;
    text.replace(QLatin1String("\r\n"), QLatin1String("\n"));
    text.replace(QLatin1String("\n"), QLatin1String("\r\n"));
    file.write(text.toUtf8());
    file.close();
    return true;
}

} // namespace

const QStringList &TemplateWriter::protectedEntries()
{
    static const QStringList entries = {
        QStringLiteral("world"),
        QStringLiteral("world_nether"),
        QStringLiteral("world_the_end"),
        QStringLiteral("plugins"),
        QStringLiteral("config"),
        QStringLiteral("mods"),
        QStringLiteral("server.properties"),
        QStringLiteral("bukkit.yml"),
        QStringLiteral("spigot.yml"),
        QStringLiteral("paper-global.yml"),
        QStringLiteral("ops.json"),
        QStringLiteral("whitelist.json"),
        QStringLiteral("banned-players.json"),
        QStringLiteral("banned-ips.json"),
    };
    return entries;
}

QString TemplateWriter::startScriptContent(const ServerRecord &record)
{
    const QString jarName = record.jarName.isEmpty() ? QStringLiteral("server.jar") : record.jarName;
    return QStringLiteral(
               "#!/bin/sh\n"
               "# generated by McServerManager - the JDK lives inside the container,\n"
               "# this script is the single entry point of the server container.\n"
               "set -e\n"
               "cd /data\n"
               "if [ ! -f \"%1\" ]; then\n"
               "  echo \"[mcsm] server jar '%1' is missing in /data\" >&2\n"
               "  exit 78\n"
               "fi\n"
               "if [ ! -f eula.txt ] || ! grep -qi 'eula=true' eula.txt; then\n"
               "  echo \"[mcsm] eula.txt must contain eula=true before the server can start\" >&2\n"
               "  exit 77\n"
               "fi\n"
               "DEFAULT_OPTS=\"-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 \"\n"
               "DEFAULT_OPTS=\"$DEFAULT_OPTS -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch \"\n"
               "DEFAULT_OPTS=\"$DEFAULT_OPTS -XX:G1HeapRegionSize=8M -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 \"\n"
               "DEFAULT_OPTS=\"$DEFAULT_OPTS -XX:G1ReservePercent=20 -XX:InitiatingHeapOccupancyPercent=15\"\n"
               "HEAP=\"-Xms${HEAP_INIT:-1G} -Xmx${MEMORY:-4G}\"\n"
               "echo \"[mcsm] starting %2 %3 with java $(java -version 2>&1 | head -n 1)\"\n"
               "exec java $HEAP $DEFAULT_OPTS ${JAVA_OPTS:-} -jar \"%1\" nogui\n")
        .arg(jarName, record.type.isEmpty() ? QStringLiteral("minecraft") : record.type,
             record.mcVersion.isEmpty() ? QStringLiteral("") : record.mcVersion);
}

bool TemplateWriter::writeStartScript(const ServerRecord &record, QString *error)
{
    const QString path = QDir(record.dir).filePath(QStringLiteral("start.sh"));
    return writeLf(path, startScriptContent(record), error);
}

bool TemplateWriter::writeEula(const ServerRecord &record, bool accepted, QString *error)
{
    const QString path = QDir(record.dir).filePath(QStringLiteral("eula.txt"));
    const QString content =
        QStringLiteral("#By changing the setting below to TRUE you are indicating your agreement to our EULA "
                       "(https://aka.ms/MinecraftEULA).\n"
                       "eula=%1\n")
            .arg(accepted ? QStringLiteral("true") : QStringLiteral("false"));
    return writeLf(path, content, error);
}

QString TemplateWriter::hostStartScriptName()
{
#ifdef Q_OS_WIN
    return QStringLiteral("start.cmd");
#else
    return QStringLiteral("start-host.sh");
#endif
}

QString TemplateWriter::hostStartScriptContent(const ServerRecord &record)
{
    const QString jarName = record.jarName.isEmpty() ? QStringLiteral("server.jar") : record.jarName;
    const QString memory = record.memory.isEmpty() ? QStringLiteral("4G") : record.memory;
    const QString options = record.effectiveJavaOptions();
    const QString comment = QStringLiteral(
        "experimental host runtime: this server runs directly on this machine with the JDK "
        "that was cloned into ./jdk when it was created.");
#ifdef Q_OS_WIN
    return QStringLiteral(
               "@echo off\r\n"
               "rem %1\r\n"
               "cd /d \"%~dp0\"\r\n"
               "if not exist \"jdk\\bin\\java.exe\" (\r\n"
               "  echo [mcsm] cloned JDK is missing - reinstall this server with host runtime\r\n"
               "  exit /b 78\r\n"
               ")\r\n"
               "if not exist \"%2\" (\r\n"
               "  echo [mcsm] server jar %2 is missing\r\n"
               "  exit /b 78\r\n"
               ")\r\n"
               "if not exist logs mkdir logs\r\n"
               "echo [mcsm] starting %DATE% %TIME% > logs\\console.log\r\n"
               "rem The server console reads stdin: with a closed stdin Minecraft prints its\r\n"
               "rem prompt in a tight loop. A long running ping keeps the pipe open instead.\r\n"
               "ping -n 1000000 127.0.0.1 > nul | \"jdk\\bin\\java.exe\" -Xms1G -Xmx%3 %4 -jar \"%2\" nogui >> logs\\console.log 2>&1\r\n")
        .arg(comment, jarName, memory, options);
#else
    return QStringLiteral(
               "#!/bin/sh\n"
               "# %1\n"
               "cd \"$(dirname \"$0\")\" || exit 78\n"
               "[ -x jdk/bin/java ] || { echo \"[mcsm] cloned JDK is missing\"; exit 78; }\n"
               "mkdir -p logs\n"
               "echo \"[mcsm] starting $(date)\" > logs/console.log\n"
               "exec jdk/bin/java -Xms1G -Xmx%2 %3 -jar \"%4\" nogui >> logs/console.log 2>&1\n")
        .arg(comment, memory, options, jarName);
#endif
}

bool TemplateWriter::writeHostStartScript(const ServerRecord &record, QString *error)
{
    const QString path = QDir(record.dir).filePath(hostStartScriptName());
#ifdef Q_OS_WIN
    return writeCrlf(path, hostStartScriptContent(record), error);
#else
    const bool ok = writeLf(path, hostStartScriptContent(record), error);
    QFile::setPermissions(path, QFile::permissions(path) | QFileDevice::ExeUser);
    return ok;
#endif
}

bool TemplateWriter::writeDefaultProperties(const ServerRecord &record, bool overwrite)
{
    const QString path = QDir(record.dir).filePath(QStringLiteral("server.properties"));
    if (QFileInfo::exists(path) && !overwrite)
        return true;
    const QVector<ConfigField> fields = ConfigSchema::fields();
    // Keys that are written explicitly below must not be emitted twice: the
    // schema loop would otherwise duplicate motd / rcon.* / ports.
    const QSet<QString> explicitKeys = {
        QStringLiteral("level-name"),  QStringLiteral("server-port"),
        QStringLiteral("rcon.port"),   QStringLiteral("rcon.password"),
        QStringLiteral("enable-rcon"), QStringLiteral("motd"),
    };
    QStringList lines;
    QString group;
    for (const ConfigField &field : fields) {
        if (explicitKeys.contains(field.key))
            continue;
        if (field.group != group) {
            group = field.group;
            lines << QStringLiteral("# %1").arg(group);
        }
        lines << QStringLiteral("%1=%2").arg(field.key, field.defaultValue);
    }
    lines << QStringLiteral("level-name=%1").arg(record.levelName.isEmpty()
                                                     ? QStringLiteral("world")
                                                     : record.levelName);
    lines << QStringLiteral("server-port=%1").arg(record.port);
    lines << QStringLiteral("rcon.port=%1").arg(record.rconPort);
    lines << QStringLiteral("rcon.password=%1").arg(record.rconPassword);
    lines << QStringLiteral("enable-rcon=true");
    lines << QStringLiteral("motd=%1").arg(record.motd.isEmpty() ? record.name : record.motd);
    return writeLf(path, lines.join(QLatin1Char('\n')) + QLatin1Char('\n'), nullptr);
}

bool TemplateWriter::writeComposeFile(const ServerRecord &record, QString *error)
{
    const QString path = QDir(record.dir).filePath(QStringLiteral("docker-compose.yml"));
    const QString content = QStringLiteral(
                                "# Generated for reference / manual runs. The GUI drives docker directly.\n"
                                "services:\n"
                                "  minecraft:\n"
                                "    image: %1\n"
                                "    container_name: %2\n"
                                "    restart: %3\n"
                                "    ports:\n"
                                "      - \"%4:%4/tcp\"\n"
                                "    environment:\n"
                                "      TZ: Asia/Shanghai\n"
                                "      MEMORY: %5\n"
                                "      JAVA_OPTS: \"%6\"\n"
                                "    volumes:\n"
                                "      - ./:/data\n"
                                "    working_dir: /data\n"
                                "    command: [\"/bin/sh\", \"/data/start.sh\"]\n")
                                .arg(record.image,
                                     record.containerName(),
                                     record.autoRestart ? QStringLiteral("unless-stopped")
                                                        : QStringLiteral("no"),
                                     QString::number(record.port),
                                     record.memory,
                                record.effectiveJavaOptions());
    return writeLf(path, content, error);
}

bool TemplateWriter::writeReadme(const ServerRecord &record, QString *error)
{
    const QString path = QDir(record.dir).filePath(QStringLiteral("README-MCSM.txt"));
    const QString content = QStringLiteral(
                                "McServerManager managed server\n"
                                "================================\n"
                                "name        : %1\n"
                                "id          : %2\n"
                                "flavour     : %3\n"
                                "minecraft   : %4\n"
                                "port        : %5\n"
                                "java image  : %6\n"
                                "memory      : %7\n"
                                "container   : %8\n\n"
                                "start.sh    : container entry point (do not add CRLF line endings)\n"
                                "backups/    : world archives created by the manager\n"
                                "config-backups/ : server.properties snapshots for rollback\n\n"
                                "Everything in this folder is mounted at /data inside the container.\n")
                                .arg(record.name, record.id, record.type, record.mcVersion,
                                     QString::number(record.port), record.image, record.memory,
                                     record.containerName());
    return writeLf(path, content, error);
}

QString TemplateWriter::compressTarCommand(const QStringList &entries, const QString &outputName)
{
    QStringList filtered;
    for (const QString &entry : entries) {
        if (entry.isEmpty())
            continue;
        filtered << QStringLiteral("\"%1\"").arg(entry);
    }
    return QStringLiteral("tar czf \"%1\" %2 2>/dev/null || true").arg(outputName, filtered.join(QLatin1Char(' ')));
}

} // namespace mcsm
